const styles = {
  form: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "30px",
    borderRadius: "10px",
    width: "90%",
    height: "90%",
    margin: "5% auto",
    boxShadow: "0 10px 20px rgba(0, 0, 0, 0.1)",
    background: "#ffffff",
  },
  step: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    width: "100%",
    height: "100%",
  },
  inputContainer: {
    position: "relative",
    width: "100%",
    marginBottom: "10px",
  },
  input: {
    width: "100%",
    padding: "12px 40px",
    margin: "5px 0",
    borderRadius: "15px",
    border: "2px solid #ddd",
    transition: "all 0.3s ease",
    fontSize: "16px",

    "&:focus": {
      borderColor: "#007bff",
      boxShadow: "0 0 0 2px rgba(0, 123, 255, 0.25)",
      outline: "none",
    },
  },
  icon: {
    position: "absolute",
    top: "50%",
    left: "15px",
    transform: "translateY(-50%)",
    color: "#007bff",
    fontSize: "18px",
  },
  buttonContainer: {
    display: "flex",
    justifyContent: "space-between",
    width: "95%",
    marginTop: "20px",
  },
  start:{
    marginBottom:"30px",
    padding:"12px 30px",
  },
  button: {
    padding: "12px 15px",
    backgroundColor: "#007bff",
    color: "white",
    border: "none",
    borderRadius: "25px",
    cursor: "pointer",
    transition: "all 0.3s ease",
    fontSize: "16px",
    fontWeight: "bold",
    textTransform: "uppercase",
    letterSpacing: "1px",
    boxShadow: "0 4px 6px rgba(0, 123, 255, 0.2)",
    "&:hover": {
      backgroundColor: "#0056b3",
      transform: "translateY(-2px)",
      boxShadow: "0 6px 8px rgba(0, 123, 255, 0.3)",
    },
    "&:active": {
      transform: "translateY(0)",
      boxShadow: "0 2px 4px rgba(0, 123, 255, 0.2)",
    },
  },
 
  progressBar: {
    width: "100%",
    height: "10px",
    backgroundColor: "#e0e0e0",
    borderRadius: "5px",
    marginBottom: "20px",
  },
  progress:{display:"none"},
  progress: {
    height: "100%",
    backgroundColor: "#007bff",
    borderRadius: "5px",
    transition: "width 0.3s ease",
  },
  image: {
    width: "300px",
    height: "auto",
    marginBottom: "20px",
  },
  loginButton: {
    marginTop: "20px",
    padding: "10px 20px",
    backgroundColor: "#28a745",
    color: "white",
    border: "none",
    borderRadius: "25px",
    cursor: "pointer",
    transition: "all 0.3s ease",
    fontSize: "14px",
    fontWeight: "bold",
    textTransform: "uppercase",
    letterSpacing: "1px",
    boxShadow: "0 4px 6px rgba(40, 167, 69, 0.2)",
    "&:hover": {
      backgroundColor: "#218838",
      transform: "translateY(-2px)",
      boxShadow: "0 6px 8px rgba(40, 167, 69, 0.3)",
    },
    "&:active": {
      transform: "translateY(0)",
      boxShadow: "0 2px 4px rgba(40, 167, 69, 0.2)",
    },
  },
  reviewContainer: {
    width: "100%",
    padding: "20px",
    backgroundColor: "#f8f9fa",
    borderRadius: "10px",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
    marginBottom: "20px",
  },
  reviewItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "10px 0",
    borderBottom: "1px solid #dee2e6",
  },
  reviewLabel: {
    fontWeight: "bold",
    color: "#495057",
  },
  reviewValue: {
    color: "#6c757d",
  },
  stepIndicator: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "40px",
    height: "40px",
    borderRadius: "50%",
    backgroundColor: "#007bff",
    color: "white",
    fontWeight: "bold",
    marginBottom: "20px",
    position: "relative",
  },
  stepNumber: {
    fontSize: "18px",
  },
  checkIcon: {
    position: "absolute",
    top: "-5px",
    right: "-5px",
    color: "#28a745",
    backgroundColor: "white",
    borderRadius: "50%",
    padding: "2px",
  },
};

export default styles;